export interface SiteSettingsDto {
  id: string;
  faviconPath: string | null;
  logoPath: string | null;
  bgColor: string;
  textColor: string;
  fontSize: number;
  fontFamily: string;
  toastMessage: string | null;
  toastDelayMs: number;
  cvFilePath: string | null;
  showPresentations: boolean;
  showSkills: boolean;
  showExperiences: boolean;
  showCertifications: boolean;
  showProjects: boolean;
  showServices: boolean;
  showAbout: boolean;
  showContact: boolean;
  showTestimonials: boolean;
  allowTestimonialSubmission: boolean;
  defaultLanguage: string;
  availabilityStatus: string;
  availabilityLabel: string | null;
  maintenanceMode: boolean;
  seoTitle: string | null;
  seoDescription: string | null;
  seoImagePath: string | null;
  notificationEmail: string | null;
  lampEnabled: boolean;
  lampOnByDefault: boolean;
  lampBeamAngle: number;
  lampIntensity: number;
  lampDimLevel: number;
  showStats: boolean;
  typeScale: "compact" | "normal" | "airy";
  lineHeight: number;
  zigzagAmplitude: number;
  sectionSpacing: number;
  animationsEnabled: boolean;
  animationSpeed: number;
  respectReducedMotion: boolean;
  cvFontFamily: string;
  accentHue: number;
  accentSaturation: number;
}
